### ISSUE TITLE
bug：shift切换中英文，英文切换中文时光标处'状态提示"不更新，无法显示"中"（要每次点击下左键才能更新）

### ISSUE THREAD

**Issue by whaohao15463** [wxd-0107/AutoHotKey#1]
系统：win10 (版本号:20H2)
输入法：搜狗智慧版(3.0)，输入习惯：双拼（小鹤双拼）

**Comment by whaohao15463** [comment]
> 系统：win10（版本号：20H2）
> 输入法：搜狗智慧版（3.0）

重新安装了搜狗输入法10.2正式版，正常了。

**Comment by whaohao15463** [comment]
> > 系统：win10（版本号：20H2）
> > 输入法：搜狗智慧版（3.0）
> 
> 重新安装了搜狗输入法10.2正式版，正常了。

不稳定:发现在"记事本，notepad++，excel，ppt"程序中可以正常切换，在其它程序（如"chrome/360浏览器、word、Foxmail、QQ"等)中文切换英文状态提示不正常[输入法已经正常切换为中文，但状态提示始终提示"英"状态].
QQ:270604631

**Comment by wxd-0107** [comment]
> > 系统：win10（版本号：20H2）
> > 输入法：搜狗智慧版（3.0）
> 
> 重新安装了搜狗输入法10.2正式版，正常了。

函数 IME_GET(WinTitle="")的返回结果，对于搜狗输入法正式版 中文为0，英文为1；而对于win10自带的输入法、小鹤双拼，以及其他版本的搜狗拼音，返回值都是1，因此导致状态显示不正常

**Comment by whaohao15463** [comment]
> > > 系统：win10（版本号：20H2）
> > > 输入法：搜狗智慧版（3.0）
> > 
> > 
> > 重新安装了搜狗输入法10.2正式版，正常了。
> 
> 函数 IME_GET(WinTitle="")的返回结果，对于搜狗输入法正式版 中文为0，英文为1；而对于win10自带的输入法、小鹤双拼，以及其他版本的搜狗拼音，返回值都是1，因此导致状态显示不正常

更新了最新版,发现在“资源管理器搜索框，Foxmail邮件正文”中输入法状态提示不能正常切换，
